[package]
name = "off-chain-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["macros"] }
candid = "0.10.6"
chrono = { version = "0.4.34", features = ["serde"] }
futures = "0.3.30"
ic-agent = "0.33.0"
rust-s3 = "0.33.0"
serde = "1.0.197"
serde_json = "1.0.114"
stringreader = "0.1.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "time"] }
openssl = { version = "0.10", features = ["vendored"] }
indicatif = { version = "0.17.8", features = ["futures"] }
tonic = { version = "0.11.0", features = ["tls-roots"] }
prost = "0.12.4"
tower = { version = "0.4", features = ["full"] }
hyper = { version = "0.14.26", features = ["full"] }
http = "0.2.11"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
headers = "0.4.0"
tonic-reflection = "0.11.0"
reqwest = { version = "0.12.3", features = ["json"] }
once_cell = "1.19.0"
yup-oauth2 = { version = "8.3.3", features = ["hyper-rustls"] }
tonic-web = "0.11.0"
log = "0.4.21"
yral-identity = { git = "https://github.com/go-bazzinga/yral-identity.git", rev = "346f61f5bf07b619be8dfc3d041dc665c4c66113" }
yral-metadata-client = { git = "https://github.com/go-bazzinga/yral-metadata.git", rev = "258a51b4c5d1152e3c045b747865eea8b6fd3096" }
yral-metadata-types = { git = "https://github.com/go-bazzinga/yral-metadata.git", rev = "258a51b4c5d1152e3c045b747865eea8b6fd3096" }
config = { version = "0.14.0", features = ["toml"] }
serde_with = "3.7.0"
thiserror = "1.0.58"
env_logger = "0.11.3"

[build-dependencies]
tonic-build = "0.11"

[[bin]]
name = "icp-off-chain-agent"
path = "src/main.rs"
