# fly.toml app configuration file generated for icp-off-chain-agent-test on 2024-04-12T17:29:18+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icp-off-chain-agent'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
PORT = '8080'
SENTRY_ENVIRONMENT = "production"
ALLOYDB_DB_NAME = "postgres"
ALLOYDB_DB_USER = "postgres"

[[services]]
internal_port = 50051
protocol = "tcp"
processes = ["app"]

[[services.ports]]
handlers = ["tls"]
tls_options = { "alpn" = ["h2"], "versions" = ["TLSv1.2", "TLSv1.3"] }
port = 443

[services.concurrency]
hard_limit = 10000
soft_limit = 50

[[vm]]
memory = '16gb'
cpu_kind = 'shared'
cpus = 8
