primary_region = 'sin'

[build]

[env]
PORT = '8080'
SENTRY_ENVIRONMENT = "staging"

[[services]]
internal_port = 50051
protocol = "tcp"
processes = ["app"]

[[services.ports]]
handlers = ["tls"]
tls_options = { "alpn" = ["h2"], "versions" = ["TLSv1.2", "TLSv1.3"] }
port = 443

[services.concurrency]
hard_limit = 1000
soft_limit = 500

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
