primary_region = 'sin'

[build]

[env]
PORT = '8080'
QSTASH_AUTH_TOKEN = 'eyJVc2VySUQiOiI4YWIwODUzNi1jOWEwLTQ3MjUtYTQ3Yi1kMDRiOGZjMWNiZjAiLCJQYXNzd29yZCI6ImVkYzNjYjI0NmNjZDQ4NjZiZDAwNTE2MWVlN2JjM2Y3In0='
QSTASH_CURRENT_SIGNING_KEY_V1 = 'sig_855AhZ49iXvFhyAU6UwsBRGyYyGQ'

[[services]]
internal_port = 50051
protocol = "tcp"
processes = ["app"]

[[services.ports]]
handlers = ["tls"]
tls_options = { "alpn" = ["h2"], "versions" = ["TLSv1.2", "TLSv1.3"] }
port = 443

[services.concurrency]
hard_limit = 1000
soft_limit = 500

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 8
