name: Upload secrets to vault

on:
  workflow_dispatch:
  push:
    branches:
      - naitik/coolify-and-vault-integration
      
permissions:
  id-token: write   
  contents: read

jobs:
  upload-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: off-chain-agent-write-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          exportToken: true
      
      - name: Install Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Set Secrets
        env:
          VAULT_ADDR: https://vault.yral.com
          HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_ACCESS_KEY_ID: ${{ secrets.HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_ACCESS_KEY_ID }}
          HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_SECRET_ACCESS_KEY: ${{ secrets.HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY: ${{ secrets.CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY }}
          YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY: ${{ secrets.YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY }}
          YRAL_OFF_CHAIN_AGENT_GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY: ${{ secrets.YRAL_OFF_CHAIN_AGENT_GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY }}
          OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN: ${{ secrets.OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN }}
          YRAL_CLOUDFLARE_WORKERS_TO_OFFCHAIN_AGENT_GRPC_AUTH_TOKEN: ${{ secrets.YRAL_CLOUDFLARE_WORKERS_TO_OFFCHAIN_AGENT_GRPC_AUTH_TOKEN }}
          YRAL_AUTH_METADATA_SERVICE_ACCESS_JWT_TOKEN_FOR_OFFCHAIN_AGENT: ${{ secrets.YRAL_AUTH_METADATA_SERVICE_ACCESS_JWT_TOKEN_FOR_OFFCHAIN_AGENT }}
          UPSTASH_VECTOR_READ_WRITE_TOKEN: ${{ secrets.UPSTASH_VECTOR_READ_WRITE_TOKEN }}
          ML_SERVER_JWT_TOKEN: ${{ secrets.ML_SERVER_JWT_TOKEN }}
          CLOUDFLARE_STREAM_READ_AND_LIST_ACCESS_TOKEN: ${{ secrets.CLOUDFLARE_STREAM_READ_AND_LIST_ACCESS_TOKEN }}
          QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
          CLOUDFLARE_IMAGES_READ_AND_WRITE_API_TOKEN: ${{ secrets.CLOUDFLARE_IMAGES_READ_AND_WRITE_API_TOKEN }}
          TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE: ${{ secrets.TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE }}
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          ML_FEED_CACHE_REDIS_URL: ${{ secrets.YRAL_ML_FEED_CACHE_REDIS_URL }}
          STORJ_INTERFACE_TOKEN: ${{ secrets.STORJ_INTERFACE_TOKEN }}
          VIDEOHASH_BACKFILL_TOKEN: ${{ secrets.VIDEOHASH_BACKFILL_TOKEN }}
          STORJ_BACKUP_CANISTER_ACCESS_GRANT: ${{ secrets.STORJ_BACKUP_CANISTER_ACCESS_GRANT }}
          CANISTER_BACKUP_ALERT_GOOGLE_CHAT_WEBHOOK_URL: ${{ secrets.CANISTER_BACKUP_ALERT_GOOGLE_CHAT_WEBHOOK_URL }}
          ALLOYDB_SERVICE_ACCOUNT_JSON_PROD: ${{ secrets.ALLOYDB_SERVICE_ACCOUNT_JSON_PROD }}
          ALLOYDB_INSTANCE_PROD: ${{ secrets.ALLOYDB_INSTANCE_PROD }}
          ALLOYDB_DB_PASSWORD_PROD: ${{ secrets.ALLOYDB_DB_PASSWORD_PROD }}
          CANISTER_BACKUP_CACHE_REDIS_URL: ${{ secrets.CANISTER_BACKUP_CACHE_REDIS_URL }}
          YRAL_METADATA_NOTIFICATION_API_KEY: ${{ secrets.YRAL_METADATA_NOTIFICATION_API_KEY }}
          ML_FEED_CACHE_MEMORYSTORE_URL: ${{ secrets.ML_FEED_CACHE_MEMORYSTORE_URL }}
          VIDEOGEN_PROVIDER_LUMALABS_API_KEY: ${{ secrets.VIDEOGEN_PROVIDER_LUMALABS_API_KEY }}
          YRAL_HON_WORKER_JWT: ${{ secrets.YRAL_HON_WORKER_JWT }}
          LEADERBOARD_REDIS_URL: ${{ secrets.LEADERBOARD_REDIS_URL }}
          SERVICE_CANISTER_MIGRATION_REDIS_URL: ${{ secrets.SERVICE_CANISTER_MIGRATION_REDIS_URL }}
          TEST_REDIS_URL: ${{ secrets.TEST_REDIS_URL }}
          HETZNER_S3_ACCESS_KEY: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
          HETZNER_S3_SECRET_KEY: ${{ secrets.HETZNER_S3_SECRET_KEY }}
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
          COMFYUI_API_URL: ${{ vars.COMFYUI_API_URL }}
          COMFYUI_VIEW_URL: ${{ vars.COMFYUI_VIEW_URL }}
          COMFYUI_API_TOKEN: ${{ secrets.COMFYUI_API_TOKEN }}
          BTC_REWARDS_GCHAT_WEBHOOK_URL: ${{ secrets.BTC_REWARDS_GCHAT_WEBHOOK_URL }}
          YRAL_OFF_CHAIN_USER_MIGRATION_API_KEY: ${{ secrets.YRAL_OFF_CHAIN_USER_MIGRATION_API_KEY }}
          ANALYTICS_SERVER_TOKEN: ${{ secrets.ANALYTICS_SERVER_TOKEN }}
          MILVUS_URL: ${{ secrets.MILVUS_URL }}
          REPLICATE_WEBHOOK_SIGNING_SECRET: ${{ secrets.REPLICATE_WEBHOOK_SIGNING_SECRET }}
          SENTRY_CLIENT_SECRET_1: ${{ secrets.SENTRY_CLIENT_SECRET_1 }}
          SENTRY_CLIENT_SECRET_2: ${{ secrets.SENTRY_CLIENT_SECRET_2 }}
          GCHAT_SENTRY_WEBHOOK_URL: ${{ secrets.GCHAT_SENTRY_WEBHOOK_URL }}
          GOOGLE_CHAT_REPORT_SPACE_URL: ${{ secrets.GOOGLE_CHAT_REPORT_SPACE_URL }}
          KVROCKS_PASSWORD: ${{ secrets.KVROCKS_PASSWORD }}
          KVROCKS_HOSTS: ${{ vars.KVROCKS_HOSTS }}
          KVROCKS_CA_CERT: ${{ secrets.KVROCKS_CA_CERT }}
          KVROCKS_CLIENT_CERT: ${{ secrets.KVROCKS_CLIENT_CERT }}
          KVROCKS_CLIENT_KEY: ${{ secrets.KVROCKS_CLIENT_KEY }}
          SCRATCHPAD_DRAGONFLY_HOST: ${{ vars.SCRATCHPAD_DRAGONFLY_HOST }}
          SCRATCHPAD_DRAGONFLY_PORT: ${{ vars.SCRATCHPAD_DRAGONFLY_PORT }}
          SCRATCHPAD_DRAGONFLY_PASSWORD: ${{ secrets.SCRATCHPAD_DRAGONFLY_PASSWORD }}
          YRAL_MOBILE_SERVICE_ACCOUNT_KEY: ${{ secrets.YRAL_MOBILE_SERVICE_ACCOUNT_KEY }}
          PROMPT_MODERATION_GEMINI_API_KEY: ${{ secrets.PROMPT_MODERATION_GEMINI_API_KEY }}
          AI_VIDEO_DETECTOR_API_KEY : ${{ secrets.AI_VIDEO_DETECTOR_API_KEY }}
        run: |
          vault kv put secret/off-chain-agent/AI_VIDEO_DETECTOR_API_KEY value="$AI_VIDEO_DETECTOR_API_KEY"
          vault kv put secret/off-chain-agent/HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_ACCESS_KEY_ID value="$HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_ACCESS_KEY_ID"
          vault kv put secret/off-chain-agent/HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_SECRET_ACCESS_KEY value="$HOT_OR_NOT_OFF_CHAIN_AGENT_CLOUDFLARE_R2_SECRET_ACCESS_KEY"
          vault kv put secret/off-chain-agent/CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY value="$CF_WORKER_ACCESS_OFF_CHAIN_AGENT_KEY"
          vault kv put secret/off-chain-agent/YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY value="$YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY"
          vault kv put secret/off-chain-agent/GOOGLYRAL_OFF_CHAIN_AGENT_GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEYE_SA_KEY value="$YRAL_OFF_CHAIN_AGENT_GOOGLE_CLOUD_SERVICE_ACCOUNT_JSON_KEY"
          vault kv put secret/off-chain-agent/OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN value="$OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN"
          vault kv put secret/off-chain-agent/YRAL_CLOUDFLARE_WORKERS_TO_OFFCHAIN_AGENT_GRPC_AUTH_TOKEN value="$YRAL_CLOUDFLARE_WORKERS_TO_OFFCHAIN_AGENT_GRPC_AUTH_TOKEN"
          vault kv put secret/off-chain-agent/YRAL_AUTH_METADATA_SERVICE_ACCESS_JWT_TOKEN_FOR_OFFCHAIN_AGENT value="$YRAL_AUTH_METADATA_SERVICE_ACCESS_JWT_TOKEN_FOR_OFFCHAIN_AGENT"
          vault kv put secret/off-chain-agent/UPSTASH_VECTOR_READ_WRITE_TOKEN value="$UPSTASH_VECTOR_READ_WRITE_TOKEN"
          vault kv put secret/off-chain-agent/ML_SERVER_JWT_TOKEN value="$ML_SERVER_JWT_TOKEN"
          vault kv put secret/off-chain-agent/CLOUDFLARE_STREAM_READ_AND_LIST_ACCESS_TOKEN value="$CLOUDFLARE_STREAM_READ_AND_LIST_ACCESS_TOKEN"
          vault kv put secret/off-chain-agent/QSTASH_CURRENT_SIGNING_KEY value="$QSTASH_CURRENT_SIGNING_KEY"
          vault kv put secret/off-chain-agent/CLOUDFLARE_IMAGES_READ_AND_WRITE_API_TOKEN value="$CLOUDFLARE_IMAGES_READ_AND_WRITE_API_TOKEN"
          vault kv put secret/off-chain-agent/TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE value="$TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE"
          vault kv put secret/off-chain-agent/QSTASH_TOKEN value="$QSTASH_TOKEN"
          vault kv put secret/off-chain-agent/ML_FEED_CACHE_REDIS_URL value="$ML_FEED_CACHE_REDIS_URL"
          vault kv put secret/off-chain-agent/STORJ_INTERFACE_TOKEN value="$STORJ_INTERFACE_TOKEN"
          vault kv put secret/off-chain-agent/VIDEOHASH_BACKFILL_TOKEN value="$VIDEOHASH_BACKFILL_TOKEN"
          vault kv put secret/off-chain-agent/STORJ_BACKUP_CANISTER_ACCESS_GRANT value="$STORJ_BACKUP_CANISTER_ACCESS_GRANT"
          vault kv put secret/off-chain-agent/CANISTER_BACKUP_ALERT_GOOGLE_CHAT_WEBHOOK_URL value="$CANISTER_BACKUP_ALERT_GOOGLE_CHAT_WEBHOOK_URL"
          vault kv put secret/off-chain-agent/ALLOYDB_SERVICE_ACCOUNT_JSON_PROD value="$ALLOYDB_SERVICE_ACCOUNT_JSON_PROD"
          vault kv put secret/off-chain-agent/ALLOYDB_INSTANCE_PROD value="$ALLOYDB_INSTANCE_PROD"
          vault kv put secret/off-chain-agent/ALLOYDB_DB_PASSWORD_PROD value="$ALLOYDB_DB_PASSWORD_PROD"
          vault kv put secret/off-chain-agent/CANISTER_BACKUP_CACHE_REDIS_URL value="$CANISTER_BACKUP_CACHE_REDIS_URL"
          vault kv put secret/off-chain-agent/YRAL_METADATA_NOTIFICATION_API_KEY value="$YRAL_METADATA_NOTIFICATION_API_KEY"
          vault kv put secret/off-chain-agent/ML_FEED_CACHE_MEMORYSTORE_URL value="$ML_FEED_CACHE_MEMORYSTORE_URL"
          vault kv put secret/off-chain-agent/VIDEOGEN_PROVIDER_LUMALABS_API_KEY value="$VIDEOGEN_PROVIDER_LUMALABS_API_KEY"
          vault kv put secret/off-chain-agent/YRAL_HON_WORKER_JWT value="$YRAL_HON_WORKER_JWT"
          vault kv put secret/off-chain-agent/LEADERBOARD_REDIS_URL value="$LEADERBOARD_REDIS_URL"
          vault kv put secret/off-chain-agent/SERVICE_CANISTER_MIGRATION_REDIS_URL value="$SERVICE_CANISTER_MIGRATION_REDIS_URL"
          vault kv put secret/off-chain-agent/TEST_REDIS_URL value="$TEST_REDIS_URL"
          vault kv put secret/off-chain-agent/HETZNER_S3_ACCESS_KEY value="$HETZNER_S3_ACCESS_KEY"
          vault kv put secret/off-chain-agent/HETZNER_S3_SECRET_KEY value="$HETZNER_S3_SECRET_KEY"
          vault kv put secret/off-chain-agent/REPLICATE_API_TOKEN value="$REPLICATE_API_TOKEN"
          vault kv put secret/off-chain-agent/COMFYUI_API_URL value="$COMFYUI_API_URL"
          vault kv put secret/off-chain-agent/COMFYUI_VIEW_URL value="$COMFYUI_VIEW_URL"
          vault kv put secret/off-chain-agent/COMFYUI_API_TOKEN value="$COMFYUI_API_TOKEN"
          vault kv put secret/off-chain-agent/BTC_REWARDS_GCHAT_WEBHOOK_URL value="$BTC_REWARDS_GCHAT_WEBHOOK_URL"
          vault kv put secret/off-chain-agent/YRAL_OFF_CHAIN_USER_MIGRATION_API_KEY value="$YRAL_OFF_CHAIN_USER_MIGRATION_API_KEY"
          vault kv put secret/off-chain-agent/ANALYTICS_SERVER_TOKEN value="$ANALYTICS_SERVER_TOKEN"
          vault kv put secret/off-chain-agent/MILVUS_URL value="$MILVUS_URL"
          vault kv put secret/off-chain-agent/REPLICATE_WEBHOOK_SIGNING_SECRET value="$REPLICATE_WEBHOOK_SIGNING_SECRET"
          vault kv put secret/off-chain-agent/SENTRY_CLIENT_SECRET_1 value="$SENTRY_CLIENT_SECRET_1"
          vault kv put secret/off-chain-agent/SENTRY_CLIENT_SECRET_2 value="$SENTRY_CLIENT_SECRET_2"
          vault kv put secret/off-chain-agent/GCHAT_SENTRY_WEBHOOK_URL value="$GCHAT_SENTRY_WEBHOOK_URL"
          vault kv put secret/off-chain-agent/GOOGLE_CHAT_REPORT_SPACE_URL value="$GOOGLE_CHAT_REPORT_SPACE_URL"
          vault kv put secret/off-chain-agent/KVROCKS_PASSWORD value="$KVROCKS_PASSWORD"
          vault kv put secret/off-chain-agent/KVROCKS_HOSTS value="$KVROCKS_HOSTS"
          vault kv put secret/off-chain-agent/KVROCKS_CA_CERT value="$KVROCKS_CA_CERT"
          vault kv put secret/off-chain-agent/KVROCKS_CLIENT_CERT value="$KVROCKS_CLIENT_CERT"
          vault kv put secret/off-chain-agent/KVROCKS_CLIENT_KEY value="$KVROCKS_CLIENT_KEY"
          vault kv put secret/off-chain-agent/SCRATCHPAD_DRAGONFLY_HOST value="$SCRATCHPAD_DRAGONFLY_HOST"
          vault kv put secret/off-chain-agent/SCRATCHPAD_DRAGONFLY_PORT value="$SCRATCHPAD_DRAGONFLY_PORT"
          vault kv put secret/off-chain-agent/SCRATCHPAD_DRAGONFLY_PASSWORD value="$SCRATCHPAD_DRAGONFLY_PASSWORD"
          vault kv put secret/off-chain-agent/YRAL_MOBILE_SERVICE_ACCOUNT_KEY value="$YRAL_MOBILE_SERVICE_ACCOUNT_KEY"
          vault kv put secret/off-chain-agent/PROMPT_MODERATION_GEMINI_API_KEY value="$PROMPT_MODERATION_GEMINI_API_KEY"